version: "3.8"

services:
  develop:
    build:
      context: .
      target: develop
    environment:
      SLACK_APP_TOKEN: ${SLACK_APP_TOKEN}
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
    volumes:
    - .:/build
  
  build:
    build:
      context: .
      target: build
    volumes:
    - .:/build/output
    command: ["cp","/build/query-bot","/build/output/"]

  app:
    build:
      context: .
      target: app
    environment:
      SLACK_TOKEN: ${SLACK_TOKEN}
    volumes:
    - ./config.yaml:/config.yaml
